"""first

Revision ID: ac7bc1a8a56c
Revises: 7d3e9c476da6
Create Date: 2025-09-26 02:17:27.255795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'ac7bc1a8a56c'
down_revision: Union[str, Sequence[str], None] = '7d3e9c476da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='answerstatus',
        new_values=['IN_PROGRESS', 'COMPLETED'],
        affected_columns=[TableReference(table_schema='public', table_name='answers', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='answerstatus',
        new_values=['IN_PROGRESS', 'SUBMITTED'],
        affected_columns=[TableReference(table_schema='public', table_name='answers', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
